// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package com.autobrain.utils;

public final class MyDataInfo {
  private MyDataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.test.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
     */
    boolean hasDataType();
    /**
     * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
     */
    MyMessage.DataType getDataType();

    /**
     * <code>optional .com.test.CodeData codeData = 2;</code>
     */
    boolean hasCodeData();
    /**
     * <code>optional .com.test.CodeData codeData = 2;</code>
     */
    CodeData getCodeData();
    /**
     * <code>optional .com.test.CodeData codeData = 2;</code>
     */
    CodeDataOrBuilder getCodeDataOrBuilder();

    /**
     * <code>optional .com.test.FileData fileData = 3;</code>
     */
    boolean hasFileData();
    /**
     * <code>optional .com.test.FileData fileData = 3;</code>
     */
    FileData getFileData();
    /**
     * <code>optional .com.test.FileData fileData = 3;</code>
     */
    FileDataOrBuilder getFileDataOrBuilder();

    public MyMessage.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code com.test.MyMessage}
   */
  public  static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.test.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      dataType_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              DataType value = DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 18: {
              CodeData.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((CodeData) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(CodeData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((CodeData) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              FileData.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((FileData) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(FileData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((FileData) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_com_test_MyMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_com_test_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.test.MyMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CodeDataType = 1;</code>
       */
      CodeDataType(1),
      /**
       * <code>FileDataType = 2;</code>
       */
      FileDataType(2),
      ;

      /**
       * <code>CodeDataType = 1;</code>
       */
      public static final int CodeDataType_VALUE = 1;
      /**
       * <code>FileDataType = 2;</code>
       */
      public static final int FileDataType_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 1: return CodeDataType;
          case 2: return FileDataType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MyMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.test.MyMessage.DataType)
    }

    private int bitField0_;
    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      CODEDATA(2),
      FILEDATA(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return CODEDATA;
          case 3: return FILEDATA;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
     */
    public DataType getDataType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.CodeDataType : result;
    }

    public static final int CODEDATA_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.test.CodeData codeData = 2;</code>
     */
    public boolean hasCodeData() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>optional .com.test.CodeData codeData = 2;</code>
     */
    public CodeData getCodeData() {
      if (dataBodyCase_ == 2) {
         return (CodeData) dataBody_;
      }
      return CodeData.getDefaultInstance();
    }
    /**
     * <code>optional .com.test.CodeData codeData = 2;</code>
     */
    public CodeDataOrBuilder getCodeDataOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (CodeData) dataBody_;
      }
      return CodeData.getDefaultInstance();
    }

    public static final int FILEDATA_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.test.FileData fileData = 3;</code>
     */
    public boolean hasFileData() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>optional .com.test.FileData fileData = 3;</code>
     */
    public FileData getFileData() {
      if (dataBodyCase_ == 3) {
         return (FileData) dataBody_;
      }
      return FileData.getDefaultInstance();
    }
    /**
     * <code>optional .com.test.FileData fileData = 3;</code>
     */
    public FileDataOrBuilder getFileDataOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (FileData) dataBody_;
      }
      return FileData.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (CodeData) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (FileData) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (CodeData) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (FileData) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyMessage)) {
        return super.equals(obj);
      }
      MyMessage other = (MyMessage) obj;

      boolean result = true;
      result = result && (hasDataType() == other.hasDataType());
      if (hasDataType()) {
        result = result && dataType_ == other.dataType_;
      }
      result = result && getDataBodyCase().equals(
          other.getDataBodyCase());
      if (!result) return false;
      switch (dataBodyCase_) {
        case 2:
          result = result && getCodeData()
              .equals(other.getCodeData());
          break;
        case 3:
          result = result && getFileData()
              .equals(other.getFileData());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + CODEDATA_FIELD_NUMBER;
          hash = (53 * hash) + getCodeData().hashCode();
          break;
        case 3:
          hash = (37 * hash) + FILEDATA_FIELD_NUMBER;
          hash = (53 * hash) + getFileData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.test.MyMessage)
        MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_com_test_MyMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_com_test_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMessage.class, Builder.class);
      }

      // Construct using com.test.MyDataInfo.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_com_test_MyMessage_descriptor;
      }

      @Override
      public MyMessage getDefaultInstanceForType() {
        return MyMessage.getDefaultInstance();
      }

      @Override
      public MyMessage build() {
        MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MyMessage buildPartial() {
        MyMessage result = new MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (codeDataBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = codeDataBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (fileDataBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = fileDataBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyMessage) {
          return mergeFrom((MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyMessage other) {
        if (other == MyMessage.getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        switch (other.getDataBodyCase()) {
          case CODEDATA: {
            mergeCodeData(other.getCodeData());
            break;
          }
          case FILEDATA: {
            mergeFileData(other.getFileData());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasDataType()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dataType_ = 1;
      /**
       * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
       */
      public DataType getDataType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.CodeDataType : result;
      }
      /**
       * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.test.MyMessage.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          CodeData, CodeData.Builder, CodeDataOrBuilder> codeDataBuilder_;
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public boolean hasCodeData() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public CodeData getCodeData() {
        if (codeDataBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (CodeData) dataBody_;
          }
          return CodeData.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return codeDataBuilder_.getMessage();
          }
          return CodeData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public Builder setCodeData(CodeData value) {
        if (codeDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          codeDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public Builder setCodeData(
          CodeData.Builder builderForValue) {
        if (codeDataBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          codeDataBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public Builder mergeCodeData(CodeData value) {
        if (codeDataBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != CodeData.getDefaultInstance()) {
            dataBody_ = CodeData.newBuilder((CodeData) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            codeDataBuilder_.mergeFrom(value);
          }
          codeDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public Builder clearCodeData() {
        if (codeDataBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          codeDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public CodeData.Builder getCodeDataBuilder() {
        return getCodeDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      public CodeDataOrBuilder getCodeDataOrBuilder() {
        if ((dataBodyCase_ == 2) && (codeDataBuilder_ != null)) {
          return codeDataBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (CodeData) dataBody_;
          }
          return CodeData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.test.CodeData codeData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CodeData, CodeData.Builder, CodeDataOrBuilder>
          getCodeDataFieldBuilder() {
        if (codeDataBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = CodeData.getDefaultInstance();
          }
          codeDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CodeData, CodeData.Builder, CodeDataOrBuilder>(
                  (CodeData) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return codeDataBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          FileData, FileData.Builder, FileDataOrBuilder> fileDataBuilder_;
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public boolean hasFileData() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public FileData getFileData() {
        if (fileDataBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (FileData) dataBody_;
          }
          return FileData.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return fileDataBuilder_.getMessage();
          }
          return FileData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public Builder setFileData(FileData value) {
        if (fileDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          fileDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public Builder setFileData(
          FileData.Builder builderForValue) {
        if (fileDataBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          fileDataBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public Builder mergeFileData(FileData value) {
        if (fileDataBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != FileData.getDefaultInstance()) {
            dataBody_ = FileData.newBuilder((FileData) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            fileDataBuilder_.mergeFrom(value);
          }
          fileDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public Builder clearFileData() {
        if (fileDataBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          fileDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public FileData.Builder getFileDataBuilder() {
        return getFileDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      public FileDataOrBuilder getFileDataOrBuilder() {
        if ((dataBodyCase_ == 3) && (fileDataBuilder_ != null)) {
          return fileDataBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (FileData) dataBody_;
          }
          return FileData.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.test.FileData fileData = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FileData, FileData.Builder, FileDataOrBuilder>
          getFileDataFieldBuilder() {
        if (fileDataBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = FileData.getDefaultInstance();
          }
          fileDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FileData, FileData.Builder, FileDataOrBuilder>(
                  (FileData) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return fileDataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.test.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.test.MyMessage)
    private static final MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyMessage();
    }

    public static MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CodeDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.test.CodeData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string yuKongID = 1;</code>
     */
    boolean hasYuKongID();
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    String getYuKongID();
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    com.google.protobuf.ByteString
        getYuKongIDBytes();

    /**
     * <code>optional string data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 2;</code>
     */
    String getData();
    /**
     * <code>optional string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code com.test.CodeData}
   */
  public  static final class CodeData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.test.CodeData)
      CodeDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CodeData.newBuilder() to construct.
    private CodeData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CodeData() {
      yuKongID_ = "";
      data_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CodeData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              yuKongID_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              data_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_com_test_CodeData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_com_test_CodeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CodeData.class, Builder.class);
    }

    private int bitField0_;
    public static final int YUKONGID_FIELD_NUMBER = 1;
    private volatile Object yuKongID_;
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    public boolean hasYuKongID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    public String getYuKongID() {
      Object ref = yuKongID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          yuKongID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getYuKongIDBytes() {
      Object ref = yuKongID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        yuKongID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile Object data_;
    /**
     * <code>optional string data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string data = 2;</code>
     */
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, yuKongID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, yuKongID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CodeData)) {
        return super.equals(obj);
      }
      CodeData other = (CodeData) obj;

      boolean result = true;
      result = result && (hasYuKongID() == other.hasYuKongID());
      if (hasYuKongID()) {
        result = result && getYuKongID()
            .equals(other.getYuKongID());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasYuKongID()) {
        hash = (37 * hash) + YUKONGID_FIELD_NUMBER;
        hash = (53 * hash) + getYuKongID().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CodeData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CodeData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CodeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CodeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CodeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CodeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CodeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CodeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CodeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CodeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CodeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CodeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CodeData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.CodeData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.test.CodeData)
        CodeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_com_test_CodeData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_com_test_CodeData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CodeData.class, Builder.class);
      }

      // Construct using com.test.MyDataInfo.CodeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        yuKongID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_com_test_CodeData_descriptor;
      }

      @Override
      public CodeData getDefaultInstanceForType() {
        return CodeData.getDefaultInstance();
      }

      @Override
      public CodeData build() {
        CodeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CodeData buildPartial() {
        CodeData result = new CodeData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.yuKongID_ = yuKongID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CodeData) {
          return mergeFrom((CodeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CodeData other) {
        if (other == CodeData.getDefaultInstance()) return this;
        if (other.hasYuKongID()) {
          bitField0_ |= 0x00000001;
          yuKongID_ = other.yuKongID_;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CodeData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CodeData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object yuKongID_ = "";
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public boolean hasYuKongID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public String getYuKongID() {
        Object ref = yuKongID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            yuKongID_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getYuKongIDBytes() {
        Object ref = yuKongID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          yuKongID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public Builder setYuKongID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        yuKongID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public Builder clearYuKongID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        yuKongID_ = getDefaultInstance().getYuKongID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public Builder setYuKongIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        yuKongID_ = value;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <code>optional string data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.test.CodeData)
    }

    // @@protoc_insertion_point(class_scope:com.test.CodeData)
    private static final CodeData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CodeData();
    }

    public static CodeData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<CodeData>
        PARSER = new com.google.protobuf.AbstractParser<CodeData>() {
      @Override
      public CodeData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CodeData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CodeData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CodeData> getParserForType() {
      return PARSER;
    }

    @Override
    public CodeData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.test.FileData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string yuKongID = 1;</code>
     */
    boolean hasYuKongID();
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    String getYuKongID();
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    com.google.protobuf.ByteString
        getYuKongIDBytes();

    /**
     * <code>repeated string package_data = 2;</code>
     */
    java.util.List<String>
        getPackageDataList();
    /**
     * <code>repeated string package_data = 2;</code>
     */
    int getPackageDataCount();
    /**
     * <code>repeated string package_data = 2;</code>
     */
    String getPackageData(int index);
    /**
     * <code>repeated string package_data = 2;</code>
     */
    com.google.protobuf.ByteString
        getPackageDataBytes(int index);
  }
  /**
   * Protobuf type {@code com.test.FileData}
   */
  public  static final class FileData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.test.FileData)
      FileDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileData.newBuilder() to construct.
    private FileData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileData() {
      yuKongID_ = "";
      packageData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              yuKongID_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                packageData_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              packageData_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          packageData_ = packageData_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_com_test_FileData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_com_test_FileData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FileData.class, Builder.class);
    }

    private int bitField0_;
    public static final int YUKONGID_FIELD_NUMBER = 1;
    private volatile Object yuKongID_;
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    public boolean hasYuKongID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    public String getYuKongID() {
      Object ref = yuKongID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          yuKongID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string yuKongID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getYuKongIDBytes() {
      Object ref = yuKongID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        yuKongID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGE_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList packageData_;
    /**
     * <code>repeated string package_data = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPackageDataList() {
      return packageData_;
    }
    /**
     * <code>repeated string package_data = 2;</code>
     */
    public int getPackageDataCount() {
      return packageData_.size();
    }
    /**
     * <code>repeated string package_data = 2;</code>
     */
    public String getPackageData(int index) {
      return packageData_.get(index);
    }
    /**
     * <code>repeated string package_data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPackageDataBytes(int index) {
      return packageData_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, yuKongID_);
      }
      for (int i = 0; i < packageData_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, packageData_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, yuKongID_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < packageData_.size(); i++) {
          dataSize += computeStringSizeNoTag(packageData_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPackageDataList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FileData)) {
        return super.equals(obj);
      }
      FileData other = (FileData) obj;

      boolean result = true;
      result = result && (hasYuKongID() == other.hasYuKongID());
      if (hasYuKongID()) {
        result = result && getYuKongID()
            .equals(other.getYuKongID());
      }
      result = result && getPackageDataList()
          .equals(other.getPackageDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasYuKongID()) {
        hash = (37 * hash) + YUKONGID_FIELD_NUMBER;
        hash = (53 * hash) + getYuKongID().hashCode();
      }
      if (getPackageDataCount() > 0) {
        hash = (37 * hash) + PACKAGE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getPackageDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FileData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FileData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FileData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FileData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FileData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FileData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FileData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.FileData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.test.FileData)
        FileDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_com_test_FileData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_com_test_FileData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FileData.class, Builder.class);
      }

      // Construct using com.test.MyDataInfo.FileData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        yuKongID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        packageData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_com_test_FileData_descriptor;
      }

      @Override
      public FileData getDefaultInstanceForType() {
        return FileData.getDefaultInstance();
      }

      @Override
      public FileData build() {
        FileData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FileData buildPartial() {
        FileData result = new FileData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.yuKongID_ = yuKongID_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          packageData_ = packageData_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.packageData_ = packageData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FileData) {
          return mergeFrom((FileData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FileData other) {
        if (other == FileData.getDefaultInstance()) return this;
        if (other.hasYuKongID()) {
          bitField0_ |= 0x00000001;
          yuKongID_ = other.yuKongID_;
          onChanged();
        }
        if (!other.packageData_.isEmpty()) {
          if (packageData_.isEmpty()) {
            packageData_ = other.packageData_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePackageDataIsMutable();
            packageData_.addAll(other.packageData_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FileData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FileData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object yuKongID_ = "";
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public boolean hasYuKongID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public String getYuKongID() {
        Object ref = yuKongID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            yuKongID_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getYuKongIDBytes() {
        Object ref = yuKongID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          yuKongID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public Builder setYuKongID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        yuKongID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public Builder clearYuKongID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        yuKongID_ = getDefaultInstance().getYuKongID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string yuKongID = 1;</code>
       */
      public Builder setYuKongIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        yuKongID_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList packageData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePackageDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          packageData_ = new com.google.protobuf.LazyStringArrayList(packageData_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPackageDataList() {
        return packageData_.getUnmodifiableView();
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public int getPackageDataCount() {
        return packageData_.size();
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public String getPackageData(int index) {
        return packageData_.get(index);
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPackageDataBytes(int index) {
        return packageData_.getByteString(index);
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public Builder setPackageData(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePackageDataIsMutable();
        packageData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public Builder addPackageData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePackageDataIsMutable();
        packageData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public Builder addAllPackageData(
          Iterable<String> values) {
        ensurePackageDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, packageData_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public Builder clearPackageData() {
        packageData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string package_data = 2;</code>
       */
      public Builder addPackageDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePackageDataIsMutable();
        packageData_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.test.FileData)
    }

    // @@protoc_insertion_point(class_scope:com.test.FileData)
    private static final FileData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FileData();
    }

    public static FileData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<FileData>
        PARSER = new com.google.protobuf.AbstractParser<FileData>() {
      @Override
      public FileData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FileData> getParserForType() {
      return PARSER;
    }

    @Override
    public FileData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_CodeData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_CodeData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_FileData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_FileData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nData.proto\022\010com.test\"\310\001\n\tMyMessage\022/\n\t" +
      "data_type\030\001 \002(\0162\034.com.test.MyMessage.Dat" +
      "aType\022&\n\010codeData\030\002 \001(\0132\022.com.test.CodeD" +
      "ataH\000\022&\n\010fileData\030\003 \001(\0132\022.com.test.FileD" +
      "ataH\000\".\n\010DataType\022\020\n\014CodeDataType\020\001\022\020\n\014F" +
      "ileDataType\020\002B\n\n\010dataBody\"*\n\010CodeData\022\020\n" +
      "\010yuKongID\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\"2\n\010FileDat" +
      "a\022\020\n\010yuKongID\030\001 \001(\t\022\024\n\014package_data\030\002 \003(" +
      "\tB\030\n\010com.testB\nMyDataInfoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_test_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_MyMessage_descriptor,
        new String[] { "DataType", "CodeData", "FileData", "DataBody", });
    internal_static_com_test_CodeData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test_CodeData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_CodeData_descriptor,
        new String[] { "YuKongID", "Data", });
    internal_static_com_test_FileData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_test_FileData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_FileData_descriptor,
        new String[] { "YuKongID", "PackageData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
